import { Profile, Post } from './types';

// Mock users for discovery feed
export const mockUsers = [
  {
    id: 'user_1',
    username: 'eric_overtone',
    profileImage: 'https://picsum.photos/150/150?random=999',
    followers: 1250,
    following: 340,
    isFollowing: false,
  },
  {
    id: 'user_2', 
    username: 'jane_photographer',
    profileImage: 'https://picsum.photos/150/150?random=998',
    followers: 890,
    following: 210,
    isFollowing: true,
  },
  {
    id: 'user_3',
    username: 'alex_creative',
    profileImage: 'https://picsum.photos/150/150?random=997',
    followers: 2100,
    following: 450,
    isFollowing: false,
  },
];

// Mock posts with different aspect ratios
export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'Misty Forest',
    caption: 'Early morning fog through ancient trees',
    imageUrl: 'https://picsum.photos/800/450?random=1',
    aspectRatio: '16:9',
    createdAt: '2024-01-15',
    tokenId: 'token_1',
    supply: 100,
    price: 0.05,
    marketCap: 5.0,
    creatorId: 'user_1',
    likes: 42,
    comments: 8,
    isLiked: false,
  },
  {
    id: '2',
    title: 'Desert Dunes',
    caption: 'Golden hour in the Sahara',
    imageUrl: 'https://picsum.photos/960/400?random=2',
    aspectRatio: '2.4:1',
    createdAt: '2024-01-14',
    tokenId: 'token_2',
    supply: 50,
    price: 0.1,
    marketCap: 5.0,
    creatorId: 'user_2',
    likes: 28,
    comments: 5,
    isLiked: true,
  },
  {
    id: '3',
    title: 'Urban Geometry',
    caption: 'Concrete and steel intersections',
    imageUrl: 'https://picsum.photos/600/600?random=3',
    aspectRatio: '4:3',
    createdAt: '2024-01-13',
    tokenId: 'token_3',
    supply: 25,
    price: 0.2,
    marketCap: 5.0,
    creatorId: 'user_3',
    likes: 67,
    comments: 12,
    isLiked: false,
  },
  {
    id: '4',
    title: 'Ocean Waves',
    caption: 'Endless blue horizon',
    imageUrl: 'https://picsum.photos/800/450?random=4',
    aspectRatio: '16:9',
    createdAt: '2024-01-12',
    tokenId: 'token_4',
    supply: 75,
    price: 0.067,
    marketCap: 5.0,
    creatorId: 'user_1',
    likes: 35,
    comments: 7,
    isLiked: true,
  },
  {
    id: '5',
    title: 'Mountain Peak',
    caption: 'Snow-capped summit at dawn',
    imageUrl: 'https://picsum.photos/960/400?random=5',
    aspectRatio: '2.4:1',
    createdAt: '2024-01-11',
    tokenId: 'token_5',
    supply: 30,
    price: 0.167,
    marketCap: 5.0,
    creatorId: 'user_2',
    likes: 89,
    comments: 15,
    isLiked: false,
  },
  {
    id: '6',
    title: 'City Lights',
    caption: 'Neon reflections on wet streets',
    imageUrl: 'https://picsum.photos/600/600?random=6',
    aspectRatio: '4:3',
    createdAt: '2024-01-10',
    tokenId: 'token_6',
    supply: 40,
    price: 0.125,
    marketCap: 5.0,
    creatorId: 'user_3',
    likes: 54,
    comments: 9,
    isLiked: true,
  },
  {
    id: '7',
    title: 'Autumn Leaves',
    caption: 'Golden foliage carpet',
    imageUrl: 'https://picsum.photos/800/450?random=7',
    aspectRatio: '16:9',
    createdAt: '2024-01-09',
    tokenId: 'token_7',
    supply: 60,
    price: 0.083,
    marketCap: 5.0,
    creatorId: 'user_1',
    likes: 73,
    comments: 11,
    isLiked: false,
  },
  {
    id: '8',
    title: 'Starry Night',
    caption: 'Milky Way over the desert',
    imageUrl: 'https://picsum.photos/960/400?random=8',
    aspectRatio: '2.4:1',
    createdAt: '2024-01-08',
    tokenId: 'token_8',
    supply: 20,
    price: 0.25,
    marketCap: 5.0,
    creatorId: 'user_2',
    likes: 156,
    comments: 23,
    isLiked: true,
  },
];

// Mock collected posts (different from owned posts)
export const mockCollectedPosts: Post[] = [
  {
    id: '101',
    title: 'Tropical Paradise',
    caption: 'Crystal clear waters and palm trees',
    imageUrl: 'https://picsum.photos/800/450?random=101',
    aspectRatio: '16:9',
    createdAt: '2024-01-07',
    tokenId: 'token_101',
    supply: 80,
    price: 0.0625,
    marketCap: 5.0,
    creatorId: 'user_3',
    likes: 92,
    comments: 18,
    isLiked: false,
  },
  {
    id: '102',
    title: 'Industrial Beauty',
    caption: 'Rust and metal textures',
    imageUrl: 'https://picsum.photos/960/400?random=102',
    aspectRatio: '2.4:1',
    createdAt: '2024-01-06',
    tokenId: 'token_102',
    supply: 35,
    price: 0.143,
    marketCap: 5.0,
    creatorId: 'user_1',
    likes: 45,
    comments: 6,
    isLiked: true,
  },
  {
    id: '103',
    title: 'Flower Garden',
    caption: 'Vibrant blooms in spring',
    imageUrl: 'https://picsum.photos/600/600?random=103',
    aspectRatio: '4:3',
    createdAt: '2024-01-05',
    tokenId: 'token_103',
    supply: 45,
    price: 0.111,
    marketCap: 5.0,
    creatorId: 'user_2',
    likes: 78,
    comments: 14,
    isLiked: false,
  },
  {
    id: '104',
    title: 'Storm Clouds',
    caption: 'Dramatic sky before the rain',
    imageUrl: 'https://picsum.photos/800/450?random=104',
    aspectRatio: '16:9',
    createdAt: '2024-01-04',
    tokenId: 'token_104',
    supply: 55,
    price: 0.091,
    marketCap: 5.0,
    creatorId: 'user_3',
    likes: 63,
    comments: 9,
    isLiked: true,
  },
];

// Mock profile
export const mockProfile: Profile = {
  id: 'user_1',
  username: 'eric_overtone',
  bio: 'I tell stories through visual media. Filmmaker, photographer, dreamer.',
  profileImageUrl: 'https://picsum.photos/150/150?random=999',
  gridLayout: '2-across-2.4:1',
  posts: mockPosts,
  collectedPosts: mockCollectedPosts,
  createdAt: '2023-12-01',
};

// Additional mock profiles for testing
export const mockProfiles: Profile[] = [
  mockProfile,
  {
    id: 'user_2',
    username: 'jane_photographer',
    bio: 'Capturing moments that matter. Street photography enthusiast.',
    profileImageUrl: 'https://picsum.photos/150/150?random=998',
    gridLayout: '1-across-16:9',
    posts: mockPosts.slice(0, 4),
    collectedPosts: mockCollectedPosts.slice(0, 2),
    createdAt: '2023-11-15',
  },
  {
    id: 'user_3',
    username: 'alex_creative',
    bio: 'Digital artist exploring the intersection of technology and nature.',
    profileImageUrl: 'https://picsum.photos/150/150?random=997',
    gridLayout: '3-across-4:3',
    posts: mockPosts.slice(2, 6),
    collectedPosts: mockCollectedPosts.slice(1, 3),
    createdAt: '2023-10-20',
  },
];
